-- Add fee columns to TitlePawns table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TitlePawns' AND COLUMN_NAME = 'TitleAndKeyFee')
BEGIN
    ALTER TABLE TitlePawns ADD TitleAndKeyFee decimal(10,2) NOT NULL DEFAULT 0.00;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TitlePawns' AND COLUMN_NAME = 'AdditionalFees')
BEGIN
    ALTER TABLE TitlePawns ADD AdditionalFees decimal(10,2) NOT NULL DEFAULT 0.00;
END;

-- Add TitleAndKeyFee column to Stores table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Stores' AND COLUMN_NAME = 'TitleAndKeyFee')
BEGIN
    ALTER TABLE Stores ADD TitleAndKeyFee decimal(10,2) NOT NULL DEFAULT 25.00;
END;
