// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTitlePawnCompany.Data;

#nullable disable

namespace MyTitlePawnCompany.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250104000000_AddRenewalTracking")]
    partial class AddRenewalTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Configuration would go here
#pragma warning restore 612, 618
        }
    }
}
