// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTitlePawnCompany.Data;

#nullable disable

namespace MyTitlePawnCompany.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250102000000_AddCustomerEmploymentAndReferences")]
    partial class AddCustomerEmploymentAndReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ... rest of the model configuration would go here
            // For brevity, this is a simplified version
#pragma warning restore 612, 618
        }
    }
}
