// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTitlePawnCompany.Data;

#nullable disable

namespace MyTitlePawnCompany.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250108000000_AddFeeFieldsToTitlePawn")]
    partial class AddFeeFieldsToTitlePawn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a partial class - the full model is in the snapshot
            // This just needs to exist for EF migrations to work
#pragma warning restore 612, 618
        }
    }
}
